/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
/* Header for class com_example_lu_jnirecorder_MainActivity */

#ifndef _Included_com_example_lu_jnirecorder_MainActivity
#define _Included_com_example_lu_jnirecorder_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lu_jnirecorder_MainActivity
 * Method:    rejnistart
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lu_jnirecorder_MainActivity_rejnistart
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lu_jnirecorder_MainActivity
 * Method:    rejnistop
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lu_jnirecorder_MainActivity_rejnistop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
